[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "navix-rubika"
version = "1.1.1"
description = "A modern, fast, and modular framework for creating Rubika bots"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "TheDevErfan" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Communications :: Chat",
]
dependencies = [
    "aiohttp>=3.8.0"
]

[project.scripts]
navix = "navix.cli:main"
