[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "navix-rubika"
version = "1.0.6"
description = "A powerful library for Rubika"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "TheDevErfan" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[dependencies]
requests = ">=2.0.0"
