[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "navix-rubika"
version = "1.0.5"
description = "An advanced asynchronous framework for Rubika bot development"
readme = "README.md"
authors = [
    { name = "TheDevErfan" }
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"
dependencies = [
    "aiohttp>=3.8.0",
    "pydantic>=2.0.0"
]

[project.urls]
Homepage = "https://github.com/TheDevErfan/navix-rubika"
